### PR TITLE
Support installation on PHP 8.x

### PR DESCRIPTION
**Pull request by tvdijen**

### CODE REVIEW

**Comment by drzraf** [comment]
Do you mind changing `.travis.yml` too, to be sure this version is tested against in the CI?

**Comment by tvdijen** [comment]
Done!

**Comment by drzraf** [comment]
@oscarotero : What do you think? Isn't the testsuite expected to run for each PR?

**Comment by tvdijen** [comment]
I think you're still relying on travis-ci.org, which has been ceased for over a year..

**Comment by oscarotero** [comment]
Hi, thanks for this.
Could `travis.yml` file be removed and use github actions? You can use the same file in Gettext main repository: https://github.com/php-gettext/Gettext/blob/master/.github/workflows/test.yaml

**Comment by oscarotero** [comment]
Thanks! Looks like the test workflow is failing.

**Pull request merged**
